### ISSUE TITLE
hmm 

### ISSUE THREAD

**Issue by NiT34ByTe** [foltone/base-foltone#4]
https://github.com/foltone/base-foltone/blob/e7eadec3a05ff142764c9a6ef503337653bb5a8d/resources/%5BJobs%5D/%5BInt%C3%A9rim%5D/esx_jobs/server/main.lua#L63

https://github.com/foltone/base-foltone/blob/e7eadec3a05ff142764c9a6ef503337653bb5a8d/resources/%5BEsx%5D/%5BAjouts%5D/esx_identity/server/main.lua#L191

https://github.com/foltone/base-foltone/blob/e7eadec3a05ff142764c9a6ef503337653bb5a8d/resources/%5BEsx%5D/%5BBase%5D/esx_property/server/main.lua#L152

Stop hiding stuff

**Comment by foltone** [comment]
I do not hide anything
this "backdoor" is not mine
and probably obsolete

**Comment by NiT34ByTe** [comment]
Then stop posting stuff that's not yours.
